function par=Parameters()

% Characteristic eqs.
par.Dc0=@(lam,b,tau,p,d,et)...
    (-1).*b+lam.*(d+lam)+p+2.*b.^(-1/2).*exp(1).^((-1/2).*(2+et) ...
  .*lam.*tau).*(b.^(1/2).*(d.*lam+p).*cosh(b.^(1/2).*(1+et).* ...
  tau)+(b.*d+lam.*p).*sinh(b.^(1/2).*(1+et).*tau)).*sinh((1/2) ...
  .*et.*lam.*tau);


par.pp=@(lam,b,tau,et)...
    (-1).*((-1)+(-1).*b.^(1/2).*exp (1).^((-1/2).*(2+et).*lam.* ...
  tau).*et.*tau.*cosh ((1/2).*et.*lam.*tau).*sinh(b.^(1/2).*(1+ ...
  et).*tau)+b.^(-1/2).*exp (1).^((-1/2).*(2+et).*lam.*tau).* ...
  et.*lam.^2.*tau.*cosh ((1/2).*et.*lam.*tau).*sinh(b.^(1/2).*( ...
  1+et).*tau)+(-4).*exp (1).^((-1/2).*(2+et).*lam.*tau).*cosh ( ...
  b.^(1/2).*(1+et).*tau).*sinh((1/2).*et.*lam.*tau)+2.*b.^( ...
  1/2).*exp (1).^((-1/2).*(2+et).*lam.*tau).*tau.*sinh (b.^(1/2) ...
  .*(1+et).*tau).*sinh((1/2).*et.*lam.*tau)+b.^(1/2).*exp(1) ...
  .^((-1/2).*(2+et).*lam.*tau).*et.*tau.*sinh (b.^(1/2).*(1+et) ...
  .*tau).*sinh((1/2).*et.*lam.*tau)+(-2).*b.^(-1/2).*exp (1).^( ...
  (-1/2).*(2+et).*lam.*tau).*lam.^2.*tau.*sinh (b.^(1/2).*(1+ ...
  et).*tau).*sinh((1/2).*et.*lam.*tau)+(-1).*b.^(-1/2).*exp(1) ...
  .^((-1/2).*(2+et).*lam.*tau).*et.*lam.^2.*tau.*sinh (b.^(1/2) ...
  .*(1+et).*tau).*sinh((1/2).*et.*lam.*tau)+(-4).*exp (1).^(( ...
  -1).*(2+et).*lam.*tau).*cosh (b.^(1/2).*(1+et).*tau).^2.* ...
  sinh ((1/2).*et.*lam.*tau).^2+4.*exp (1).^((-1).*(2+et).*lam.* ...
  tau).*sinh (b.^(1/2).*(1+et).*tau).^2.*sinh ((1/2).*et.*lam.* ...
  tau).^2).^(-1).*(2.*lam.*(lam+2.*exp (1).^((-1/2).*(2+et).* ...
  lam.*tau).*lam.*cosh (b.^(1/2).*(1+et).*tau).*sinh((1/2).* ...
  et.*lam.*tau)+2.*b.^(1/2).*exp (1).^((-1/2).*(2+et).*lam.* ...
  tau).*sinh (b.^(1/2).*(1+et).*tau).*sinh((1/2).*et.*lam.*tau) ...
  )+(-1).*((-1).*b+lam.^2).*(1+exp (1).^((-1/2).*(2+et).*lam.* ...
  tau).*et.*lam.*tau.*cosh (b.^(1/2).*(1+et).*tau).*cosh((1/2) ...
  .*et.*lam.*tau)+b.^(1/2).*exp (1).^((-1/2).*(2+et).*lam.*tau) ...
  .*et.*tau.*cosh ((1/2).*et.*lam.*tau).*sinh(b.^(1/2).*(1+et) ...
  .*tau)+2.*exp (1).^((-1/2).*(2+et).*lam.*tau).*cosh (b.^(1/2) ...
  .*(1+et).*tau).*sinh((1/2).*et.*lam.*tau)+(-1).*exp (1).^(( ...
  -1/2).*(2+et).*lam.*tau).*(2+et).*lam.*tau.*cosh (b.^(1/2).*( ...
  1+et).*tau).*sinh((1/2).*et.*lam.*tau)+(-1).*b.^(1/2).*exp ( ...
  1).^((-1/2).*(2+et).*lam.*tau).*(2+et).*tau.*sinh (b.^(1/2).* ...
  (1+et).*tau).*sinh((1/2).*et.*lam.*tau)));


par.dd=@(lam,b,tau,et)...
   (-1).*exp (1).^((1/2).*(2+et).*lam.*tau).*(2.*b.^(1/2).*exp ( ...
  1).^((1/2).*(2+et).*lam.*tau).*lam+b.^(3/2).*et.*tau.*cosh ( ...
  b.^(1/2).*(1+et).*tau).*cosh((1/2).*et.*lam.*tau)+(-1).*b.^( ...
  1/2).*et.*lam.^2.*tau.*cosh (b.^(1/2).*(1+et).*tau).*cosh(( ...
  1/2).*et.*lam.*tau)+b.*et.*lam.*tau.*cosh ((1/2).*et.*lam.* ...
  tau).*sinh(b.^(1/2).*(1+et).*tau)+(-1).*et.*lam.^3.*tau.* ...
  cosh ((1/2).*et.*lam.*tau).*sinh(b.^(1/2).*(1+et).*tau)+4.* ...
  b.^(1/2).*lam.*cosh (b.^(1/2).*(1+et).*tau).*sinh((1/2).*et.* ...
  lam.*tau)+(-2).*b.^(3/2).*tau.*cosh (b.^(1/2).*(1+et).*tau).* ...
  sinh((1/2).*et.*lam.*tau)+(-1).*b.^(3/2).*et.*tau.*cosh (b.^( ...
  1/2).*(1+et).*tau).*sinh((1/2).*et.*lam.*tau)+2.*b.^(1/2).* ...
  lam.^2.*tau.*cosh (b.^(1/2).*(1+et).*tau).*sinh((1/2).*et.* ...
  lam.*tau)+b.^(1/2).*et.*lam.^2.*tau.*cosh (b.^(1/2).*(1+et).* ...
  tau).*sinh((1/2).*et.*lam.*tau)+2.*b.*sinh (b.^(1/2).*(1+et) ...
  .*tau).*sinh((1/2).*et.*lam.*tau)+2.*lam.^2.*sinh (b.^(1/2).* ...
  (1+et).*tau).*sinh((1/2).*et.*lam.*tau)+(-2).*b.*lam.*tau.* ...
  sinh (b.^(1/2).*(1+et).*tau).*sinh((1/2).*et.*lam.*tau)+(-1) ...
  .*b.*et.*lam.*tau.*sinh (b.^(1/2).*(1+et).*tau).*sinh((1/2).* ...
  et.*lam.*tau)+2.*lam.^3.*tau.*sinh (b.^(1/2).*(1+et).*tau).* ...
  sinh((1/2).*et.*lam.*tau)+et.*lam.^3.*tau.*sinh (b.^(1/2).*( ...
  1+et).*tau).*sinh((1/2).*et.*lam.*tau)).*(b.^(1/2).*exp(1) ...
  .^((2+et).*lam.*tau)+b.*exp (1).^((1/2).*(2+et).*lam.*tau).* ...
  et.*tau.*cosh ((1/2).*et.*lam.*tau).*sinh(b.^(1/2).*(1+et).* ...
  tau)+(-1).*exp (1).^((1/2).*(2+et).*lam.*tau).*et.*lam.^2.* ...
  tau.*cosh ((1/2).*et.*lam.*tau).*sinh(b.^(1/2).*(1+et).*tau)+ ...
  4.*b.^(1/2).*exp (1).^((1/2).*(2+et).*lam.*tau).*cosh (b.^( ...
  1/2).*(1+et).*tau).*sinh((1/2).*et.*lam.*tau)+(-2).*b.*exp ( ...
  1).^((1/2).*(2+et).*lam.*tau).*tau.*sinh (b.^(1/2).*(1+et).* ...
  tau).*sinh((1/2).*et.*lam.*tau)+(-1).*b.*exp (1).^((1/2).*(2+ ...
  et).*lam.*tau).*et.*tau.*sinh (b.^(1/2).*(1+et).*tau).*sinh(( ...
  1/2).*et.*lam.*tau)+2.*exp (1).^((1/2).*(2+et).*lam.*tau).* ...
  lam.^2.*tau.*sinh (b.^(1/2).*(1+et).*tau).*sinh((1/2).*et.* ...
  lam.*tau)+exp (1).^((1/2).*(2+et).*lam.*tau).*et.*lam.^2.* ...
  tau.*sinh (b.^(1/2).*(1+et).*tau).*sinh((1/2).*et.*lam.*tau)+ ...
  4.*b.^(1/2).*cosh (b.^(1/2).*(1+et).*tau).^2.*sinh ((1/2).* ...
  et.*lam.*tau).^2+(-4).*b.^(1/2).*sinh(b.^(1/2).*(1+et).*tau) ...
  .^2.*sinh ((1/2).*et.*lam.*tau).^2).^(-1);

% par.Dc1=@(lam,b,tau,p,d,et)...
%     d+2.*lam+b.^(-1/2).*exp(1).^((-1/2).*(2+et).*lam.*tau).*et.* ...
%   tau.*cosh((1/2).*et.*lam.*tau).*(b.^(1/2).*(d.*lam+p).*cosh( ...
%   b.^(1/2).*(1+et).*tau)+(b.*d+lam.*p).*sinh(b.^(1/2).*(1+et) ...
%   .*tau))+2.*b.^(-1/2).*exp(1).^((-1/2).*(2+et).*lam.*tau).*( ...
%   b.^(1/2).*d.*cosh(b.^(1/2).*(1+et).*tau)+p.*sinh(b.^(1/2).*( ...
%   1+et).*tau)).*sinh((1/2).*et.*lam.*tau)+(-1).*b.^(-1/2).* ...
%   exp(1).^((-1/2).*(2+et).*lam.*tau).*(2+et).*tau.*(b.^(1/2).* ...
%   (d.*lam+p).*cosh(b.^(1/2).*(1+et).*tau)+(b.*d+lam.*p).*sinh( ...
%   b.^(1/2).*(1+et).*tau)).*sinh((1/2).*et.*lam.*tau);
% 
% 
par.Dc2=@(lam,b,tau,p,d,et)...
    2+(1/2).*b.^(-1/2).*exp(1).^((-1/2).*(2+et).*lam.*tau).*(2+ ...
  et).^2.*tau.^2.*(b.^(1/2).*(d.*lam+p).*cosh(b.^(1/2).*(1+et) ...
  .*tau)+(b.*d+lam.*p).*sinh(b.^(1/2).*(1+et).*tau)).*sinh(( ...
  1/2).*et.*lam.*tau)+(-2).*b.^(-1/2).*exp(1).^((-1/2).*(2+et) ...
  .*lam.*tau).*(2+et).*tau.*((1/2).*et.*tau.*cosh((1/2).*et.* ...
  lam.*tau).*(b.^(1/2).*(d.*lam+p).*cosh(b.^(1/2).*(1+et).* ...
  tau)+(b.*d+lam.*p).*sinh(b.^(1/2).*(1+et).*tau))+(b.^(1/2).* ...
  d.*cosh(b.^(1/2).*(1+et).*tau)+p.*sinh(b.^(1/2).*(1+et).* ...
  tau)).*sinh((1/2).*et.*lam.*tau))+2.*b.^(-1/2).*exp(1).^(( ...
  -1/2).*(2+et).*lam.*tau).*(et.*tau.*cosh((1/2).*et.*lam.* ...
  tau).*(b.^(1/2).*d.*cosh(b.^(1/2).*(1+et).*tau)+p.*sinh(b.^( ...
  1/2).*(1+et).*tau))+(1/4).*et.^2.*tau.^2.*(b.^(1/2).*(d.* ...
  lam+p).*cosh(b.^(1/2).*(1+et).*tau)+(b.*d+lam.*p).*sinh(b.^( ...
  1/2).*(1+et).*tau)).*sinh((1/2).*et.*lam.*tau));


end